### ISSUE TITLE
Don't try to auto update if the data service can't be stopped

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#614]
Right now, on automatic update, if this error occurs:
```
[2023-10-24T08:24:11.398Z] ERROR    ZitiUpdateService.UpdateService    Timout while trying to stop service!    System.InvalidOperationException: Cannot stop ziti service on computer '.'. ---> System.ComponentModel.Win32Exception: The service has not been started
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Stop()
   at ZitiUpdateService.UpdateService.StopZiti()
```

The application will continuously try to update but never succeed because the data service is hung somehow. The user will need to restart Windows, or terminate the `ziti-edge-tunnel` service before updating can continue. This should be logged and probably surfaced as an error/message to the user to reboot/take action.

**Comment by dovholuknf** [comment]
the monitor service will forcefully terminate the data service now
