### ISSUE TITLE
slice bounds out of range [2:1]

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#96]
looks like a concurrency issue when adding/updating/removing from services. panic just happened when renaming a service:

```
[ 137.642]   DEBUG :  dispatched remove service change event
panic: runtime error: slice bounds out of range [2:1]

goroutine 11 [running]:
github.com/openziti/desktop-edge-win/service/ziti-tunnel/service.acceptServices()
        C:/Users/travis/gopath/src/github.com/openziti/desktop-edge-win/service/ziti-tunnel/service/ipc.go:845 +0xb17
created by github.com/openziti/desktop-edge-win/service/ziti-tunnel/service.SubMain
        C:/Users/travis/gopath/src/github.com/openziti/desktop-edge-win/service/ziti-tunnel/service/ipc.go:91 +0x352
```

**Comment by dovholuknf** [comment]
not seen for a very long time - numerous changes since this bug report likely fixed it. reopen if needed
